configName: pic32cz_ca80_curiosity_ultra_freertos
folderName: pic32cz_ca80_curiosity_ultra_freertos
format_version: v1.0
frameworkPath: ..\..\..\..\..\..\..\harmony
processor: PIC32CZ8110CA80208
projectName: usart_echo_pic32cz_ca80_curiosity_ultra_freertos
settings:
  PackageFilter: audio;bootloader;bsp;core;core_apps_pic32cz_ca;core_apps_sam_d21_da1;crypto;cryptoauthlib;csp;gfx;mbed_os_rtos;mbed_os_rtos_apps;micrium_ucos3;motor_control;net;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CZ-CA_DFP\0.0.62\CA90\atdf\PIC32CZ8110CA80208.atdf
