package:
  format-version: "1.0.0"
  name: "core_apps_pic32cz_ca"
  version: "v3.0.0-eng.1"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.11.1"
    - name: "csp"
      type: "package"
      version: "v3.15.0-eng.1"


