configName: pic32cz_ca80_curiosity_ultra
folderName: pic32cz_ca80_curiosity_ultra
format_version: v1.0
frameworkPath: ..\..\..\..\..\..
processor: PIC32CZ8110CA80208
projectName: i2c_eeprom_pic32cz_ca80_curiosity_ultra
settings:
  PackageFilter: bootloader;bsp;core;csp;Devices;dev_packs;harmony-services;motor_control;quick_docs;usb;wireless_wifi;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CZ-CA80_DFP\1.0.17\CA80\atdf\PIC32CZ8110CA80208.atdf
