format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32Z_CA90_Curiosity_Ultra, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '390', y: '100', id: BSP_PIC32Z_CA90_Curiosity_Ultra}
