format_version: v1.0
type: UniqueComponent
attributes: {id: drv_at24}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_AT24_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_at24, value: SERCOM5}
  - type: Integer
    attributes: {id: EEPROM_ADDR_LEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_at24, value: '2'}
  - type: Integer
    attributes: {id: EEPROM_FLASH_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '262144'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_at24_I2C_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sercom5}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SERCOM5_I2C}
- type: ElementPosition
  attributes: {x: '446', y: '131', id: drv_at24}
